- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start and enable the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enbaled: yes