- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATON: 120hrs
    TRAINER: sivakumar
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }} trainer is {{ TRAINER }}"