- name: filters
  hosts: web
  become: yes
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello from {{ person | default('sai') }}"
  
  - name: convert string to list
    vars:
      FRUITS: "goa, apple, banana"
    ansible.builtin.debug:
      msg: "fruits are: {{ FRUITS | split(',') }}"

  - name: convert map into list
    vars:
      COURSE:
        name: ansible
        duration: 120hrs
    ansible.builtin.debug:
      msg: "course details {{ COURSE | dict2items }}"
    
  - name: check ip address is valid or not
    vars:
      IP: 286.245.265.241
    ansible.builtin.debug:
      msg: "ip is {{ IP | ansible.utils.ipaddr }}"