[web]
172.31.22.47 COURSE="DevOps with AWS" DURATION=120hrs TRAINER=sivakumar
; localhost COURSE=Terraform DURATION=120hrs TRAINER=sivakumar

[local]
localhost

[backend]
10.1.1.1
10.1.1.1
10.1.1.1
10.1.1.1
10.1.1.1
10.1.1.1
10.1.1.1
10.1.1.1

[local:vars]
; GREET=inventory
; COURSE="Devops with aws"
; DURATION=120hrs
; TRAINER=sivakumar
